#pragma config(Sensor, in1,    lArmPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    rArmPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    lPivotPot,      sensorPotentiometer)
#pragma config(Sensor, in4,    rPivotPot,      sensorPotentiometer)
#pragma config(Motor,  port2,           rFrontMotor,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           rBackMotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           lFrontMotor,   tmotorVex393, openLoop)
#pragma config(Motor,  port5,           lBackMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           lArmMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rArmMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 2198Y Drive Program
// Last Updated by Tony T on 2016-11-04

task main()
{

	// create calibration integers
	int lOffset = 0;
	int rOffset = 1;

  while(1 == 1)
  {

  		// Assign sensor inputs to variables
		int lArm = (SensorValue[lArmPot] - lOffset); // LARM MINUS THE OFFSER (TO CALIBRATE)
  	int rArm = (SensorValue[rArmPot] - rOffset); // ALSO NEGATES THE POTENTIOMETER

   	int motorspeed = abs(lArm - rArm); // Create variable to change motor speed based on how different the readings are


    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[rFrontMotor] = vexRT[Ch2];
    motor[rBackMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[lFrontMotor] = vexRT[Ch3];
    motor[lBackMotor]  = vexRT[Ch3];

  //  if (vexRT[Btn7R])
  //{
  //	motor[rArmMotor] = 127;
  //}
  //if (vexRT[Btn7U])
  //{
  //	motor[lArmMotor] = 127;
  //}
  //if (vexRT[Btn7L])
  //{
  //	motor[lArmMotor] = 127;
  //}

	if (vexRT[Btn5D] == 1)
	{
		if (lArm == rArm)
			{
			motor[rArmMotor] = 127;
			motor[lArmMotor] = 127;
		}

		else if (lArm > rArm)
			{
			motor[rArmMotor] = 127;
			motor[lArmMotor] = (127 - motorspeed*2);
		}

		else {
			motor[rArmMotor] = (127 - motorspeed*2);
			motor[lArmMotor] = 127;
		}
	}

	else if (vexRT[Btn6D] == 1)
	{
		if (lArm == rArm)
			{
			motor[rArmMotor] = -127;
			motor[lArmMotor] = -127;
		}

		else if (lArm > rArm)
			{
			motor[rArmMotor] = (-127 + motorspeed*2);
			motor[lArmMotor] = -127;
		}

		else
			{
			motor[rArmMotor] = -127;
			motor[lArmMotor] = (-127 + motorspeed*2);
		}
	}

   else
     {
	   motor[lArmMotor] = 0;
	   motor[rArmMotor] = 0;
   }


    // Pivot System

  }
}

/* Changelogs

v1.0.0 		2016-11-01		Created 4 motor drive program
v1.0.1		2016-11-01		Reversed right motors
v2.0.0		2016-11-02		Started arm motor program
v2.0.1		2016-11-02		Added pragma config for arms
v2.1.0		2016-11-02		Added code for arm to go up based on buttons
v2.1.1		2016-11-03		Added potentiometers into pragma config
v3.0.0		2016-11-04		Potentiometer code active
v3.1.0		2016-11-07		Changed joystick buttons
v3.2.0		2016-11-07		Added variables for offset, included potentiometer readings into loop
v3.2.x		2016-11-07		Attempt to fix potentiometers
v4.0.0		2016-11-07		New potentiometer code
*/
