#pragma config(Sensor, dgtl1,  eggSelectInput,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  color1,              sensorDigitalIn)
#pragma config(Sensor, dgtl3,  color0,              sensorDigitalIn)
#pragma config(Sensor, dgtl4,  reedSwitch,          sensorDigitalIn)
#pragma config(Motor,  port1,           left,          tmotorNormal, openLoop)
#pragma config(Motor,  port2,           ballColor,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftClaw,      tmotorNormal, openLoop)
#pragma config(Motor,  port4,           leftArm,       tmotorNormal, openLoop)
#pragma config(Motor,  port5,           eggType,       tmotorNormal, openLoop)
#pragma config(Motor,  port6,           ,              tmotorNormal, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           rightClaw,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           ,              tmotorNormal, openLoop)
#pragma config(Motor,  port10,          right,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
//
// Include the file that contains the library of functions for driving the robot and moving servos. Some of
// these function will be used here.
//
#include "BEST_Function_Library.h"


static void detechGolfBallSwitchSettings();  // Prototype declaration to avoid "undefined" error.

task main()
{
  //
  // Adjust the size of the joysticks dead band. Use this if your joystick does not center on (0, 0) to
  // prevent the motor humming and not moving.
  //
  nDeadBandSize = 10;  // Any joystick values in the range - 10 to +10 will be considered same as zero.


  while (true)
  {
    // Drive the robot

    ArcadeTwoWheelDrive(vexJSLeftV, vexJSLeftH, left, right);
    //TankTwoWheelDrive(vexJSLeftV, vexJSRightV, left, right);


    // Left Arm control

    // Move the Left arm motor
    MotorControlViaDigitalButtons(Btn7D,      // The joystick button that controls speed decrease
                                  Btn7U,      // The joystick button that controls speed increase
                                  leftArm,    // The motor that is being controlled
                                  -127,       // The lowest  value for the motor speed
                                  +127,       // The highest value for the motor speed
                                  0);         // How fast to adjust the speed. 0 -- fastest. 50 -- 1.25 seconds to cover the compete range.

    // Open and close the Left claw servo
    ServoControlViaDigitalButtons(Btn7L,      // The joystick button that controls downward movement
                                  Btn7R,      // The joystick button that controls upward movement
                                  leftClaw,   // The servo that is being controlled
                                  -127,       // The lowest DOWN value for the servo position / motor speed
                                  +127,       // The highest UP value for the servo position / motor speed
                                  0);


    // Right Arm control

    // Move the Right arm motor
    MotorControlViaDigitalButtons(Btn8D,      // The joystick button that controls speed decrease
                                  Btn8U,      // The joystick button that controls speed increase
                                  rightArm,   // The motor that is being controlled
                                  -127,       // The lowest  value for the motor speed
                                  +127,       // The highest value for the motor speed
                                  0);         // How fast to adjust the speed. 0 -- fastest. 50 -- 1.25 seconds to cover the compete range.

    // Open and close the Right claw servo
    ServoControlViaDigitalButtons(Btn8L,      // The joystick button that controls downward movement
                                  Btn8R,      // The joystick button that controls upward movement
                                  rightClaw,  // The servo that is being controlled
                                  -127,       // The lowest DOWN value for the servo position
                                  +127,       // The highest UP value for the servo position / motor speed
                                  0);         // How fast to adjust the speed. 0 -- fastest. 50 -- 1.25 seconds to cover the compete range.

    detechGolfBallSwitchSettings();
  }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                Sample Code to Handle the 3-switches for the BEST 2010 Competition
//
//  The color of golf ball to reject is determined by reading two switches. Depending on the switch setting the
//  color can be:
//         Switch 1             Switch 0
//    Open Ckt (value 1)   Open Ckt (value 1)   11   3    "No connection"
//    Open Ckt (value 1)   Ground   (value 0)   10   2    "Reject White"
//    Ground   (value 0)   Open Ckt (value 1)   01   1    "Reject Yellow"
//    Ground   (value 0)   Ground   (value 0)   00   0    "Reject Black"
//
//  The type of Egg to collect:
//         Switch 2
//    Open Ckt (value 1)                                  "With Magnet inside"
//    Ground   (value 0)                                  "No Magnet inside"
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

typedef enum // defines a list of 'friendly names' to represent the types of eggs to collect
{
  eggsWithMagnets       = 0,
  eggsWithoutMagnets    = 1
} TEggTypes;

typedef enum // defines a list of 'friendly names' to represent the color of golf balls to reject
{
  rejectBlack       = 0,
  rejectYellow      = 1,
  rejectWhite       = 2,
  noConnection      = 3

} TGolfballs;

TEggTypes sensorEggType = eggsWithMagnets;  // Default value

int colorBit0 = 1;    // '1's digit of two-bit binary number
int colorBit1 = 2;    // '2's digit of two-bit binary number

TGolfballs golfBallColor  = noConnection;  // Default value


void detechGolfBallSwitchSettings()
{
  //
  // Detect the three switches. Latch the changes
  //    -- Value 0 of "sensor" when open  circuit
  //    -- Value 1 of "sensor" when short circuited to ground

  if (SensorValue[eggSelectInput] == 0)
    sensorEggType = eggsWithoutMagnets;  // Switch is closed. Change value. Check this to ensure not reversed.

  if (SensorValue[color0] == 0)
    colorBit0 = 0;                  // Switch is closed. Change value

  if (SensorValue[color1] == 0)
    colorBit1 = 0;                  // Switch is closed. Change value

   golfBallColor = (TGolfballs) (colorBit0 + colorBit1); // Stored as a two bit binary number

   //
   // Move the servo to indicate what color golf ball is detected.
   //
   switch (golfBallColor)
   {
   case rejectBlack:          motor[ballColor] =    0;   break;
   case rejectYellow:         motor[ballColor] = -127;   break;
   case rejectWhite:          motor[ballColor] = +127;   break;
   case noConnection:         break;
   default:                   break;
   }
   //
   // Move the servo to indicate what type of egg is detected.
   //
   switch (sensorEggType)
   {
   case eggsWithMagnets:      motor[eggType] = +127;   break;
   case eggsWithoutMagnets:   motor[eggType] = -127;   break;
   default:                   break;
   }
}
