#pragma config(Sensor, dgtl1,  magnet,              sensorDigitalIn)
#pragma config(Sensor, dgtl2,  color1,              sensorDigitalIn)
#pragma config(Sensor, dgtl3,  color0,              sensorDigitalIn)
#pragma config(Motor,  port1,           LeftMotor,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           ballColor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           LeftClaw,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           LeftArm,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           RightArm,      tmotorNormal, openLoop)
#pragma config(Motor,  port8,           RightClaw,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           Magnet,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          RightMotor,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - ADVANCED Single Joystick Control -                                *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*    3)  'abs(z)' is the ABSOLUTE VALUE of 'z'.                                                      *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
  typedef enum // defines a list of 'friendly names'
  {
    eggsWithMagnets       = 0,
    eggsWithoutMagnets    = 1
  } TEggTypes;

  typedef enum
  {
    rejectblack   =0,
    rejectyellow  =1,
    rejectwhite   =2,
    noconnection   = 3

  } TGolfballs;

  TEggTypes sensorEggType = eggsWithMagnets;

  int colorBit0 = 1;
  int colorBit1 = 2;

  TGolfballs golfBallColor  = noconnection;


  while(1 == 1)
  {
    motor[RightMotor] = vexRT[Ch2];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
    motor[LeftMotor] = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.


    //
    //Control Arms
    //
    if (vexRT[Btn6U]==1)
    {
      motor[LeftClaw]= 127;
    }
    else if (vexRT[Btn6D]==1)
    {
      motor[LeftClaw]= -127;
    }
    else
    {
      motor[LeftClaw]=0;
    }

    if (vexRT[Btn8L]==1)
    {
      motor[RightClaw]= 127;
    }
    else if (vexRT[Btn8R]==1)
    {
      motor[RightClaw]= -127;
    }
    else
    {
      motor[RightClaw]=0;
    }

    if (vexRT[Btn5U]==1)
    {
      motor[LeftArm]= 90;
    }
    else if (vexRT[Btn5D]==1)
    {
      motor[LeftArm]=-90;
    }
    else
    {
      motor[LeftArm]=0;
    }

    if (vexRT[Btn8U]==1)
    {
      motor[RightArm]=90;
    }
    else if (vexRT[Btn8D]==1)
    {
      motor[RightArm]=-90;
    }
    else
    {
      motor[RightArm]=0;
    }


    //
    // Detect the three switches
    //

    if (SensorValue[magnet] == 0)
      sensorEggType = eggsWithoutMagnets;

    if (SensorValue[color0] == 0)
      colorBit0 = 0;

    if (SensorValue[color1] == 0)
      colorBit1 = 0;

    //
    //Reset sensor values and servos
    //

    if ((vexRT[Btn6U]==1) && (vexRT[Btn5U]==1) && (vexRT[Btn5D]==1) && (vexRT[Btn6D]==1))
    {
      sensorEggType = eggsWithMagnets;
      colorBit0 = 1;
      colorBit1 = 2;
      if (golfBallColor == rejectblack)
      {
        motor[ballColor] = 0;
      }
      else if (golfBallColor == rejectwhite)
      {
        motor[ballColor] = -127;
      }
      else if (golfBallColor == rejectyellow)
      {
        motor[ballColor] = 127;
      }
      else
      {
        motor[ballColor] =0;
      }
    }

    golfBallColor = (TGolfballs)(colorBit0 + colorBit1);

    switch (sensorEggType)
    {
    case eggsWithMagnets:    motor[Magnet] = 0;     break;
    case eggsWithoutMagnets: motor[Magnet] = 127;   break;
    default:                                        break;
    }
    switch (golfBallColor)
    {
    case rejectblack:        motor[ballColor] =    0;   break;
    case rejectyellow:       motor[ballColor] = -127;   break;
    case rejectwhite:        motor[ballColor] = +127;   break;
    case noconnection:                                  break;
    default:               break;
    }
  }

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
