#pragma config(Motor,  port1,           frontRight,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontTshoot,   tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port3,           backTshoot,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           Intakes,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           conveyor,      tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port8,           frontBshoot,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port9,           backBshoot,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          backRight,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int autospeed=70;

task main()
{
	ClearTimer(t1);
	while (time1[t1]<15000)
	{
			motor[frontTshoot]=autospeed;
			motor[backTshoot]=autospeed;
	    motor[frontBshoot]=autospeed;
	    motor[backBshoot]=autospeed;

		if (time1[t1]>3650 && time1[t1]<4200)
		{
			motor[conveyor] = 80;
		}

		else if (time1[t1]>6600 && time1[t1]<7175)
		{
			motor[conveyor] = 127;
		}

		else if (time1[t1]>9600 && time1[t1]<10150)
		{
			motor[conveyor] = 127;
		}

		else if (time1[t1]>10200 && time1[t1]<10201)
		{
			autospeed=72;
		}

		else if (time1[t1]>12800 && time1[t1]<13300)
		{
			motor[conveyor] = 100;
		}
		else
		{
			motor[conveyor]=0;
		}



	}
}
