#pragma config(UART_Usage, UART1, CMU_Camera)
#pragma config(UART_Usage, UART2, User_Control)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////////////
//
//                CMUCAM Operation with VEX and FRC Controllers
//
//////////////////////////////////////////////////////////////////////////////////////////////

#pragma platform(VEX2)
//
// Load the "configuration program" generated camera  settings
//
#include "cameraConfiguration.h"


task main()
{
	int nNumbOfPackets = 0;
	int nNewPacketCount = 0;
  float fFrameRate = 0;
	int simpleData[(TCameraSources) 4];
	TTrackingDataWords camData;

	//
	// Startup the CMUCAM. It can take several seconds to stabilize, so wait a little bit
	//
	wait1Msec(1000);   // Let the camera stabilize

	time1[T1] = 0;
	while (true)
	{
		//
		// CMUCAM is continuously getting "tracking" information. It is received as a packet of data
		// from the camera. About 30 packets per second are received.
		//
		// We don't want to work with partial data
		// from packet "N" and partial data from packet "N+1". So copy the last completely received
		// tracking packet so that a consistent "packet" can be used within our program.
		//
		GetTrackingParms(camData);
		//
		// Calculate the frame rate
		//
		nNumbOfPackets = camData.nTrackingPacketsRcvd - nNewPacketCount;
		if (nNumbOfPackets != 0)
		{
			float fTimeInterval;

			nNewPacketCount = camData.nTrackingPacketsRcvd;
			fTimeInterval = time1[T1];
			fFrameRate = 1000 / fTimeInterval * nNumbOfPackets;
			time1[T1] = 0;
		}
		simpleData[camVertical]      = nCameraVertical;
		simpleData[camHorizontal]    = nCameraHorizontal;
		simpleData[camNumbTrackingRecords] = nCameraTrackingPackets;
		simpleData[camConfidence]    = nCameraConfidence;

	}
	StopCamera();
}
