//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - Program Chooser (live) -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program takes the content of "Program Chooser.c" and uses it in a separate task running      *|
|*  alongside your own code.  If you apply this template to all of your programs, you can run         *|
|*  programs "on the fly" or in succession without having to power cycle.                             *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  LCD connected to both RX and TX of UART 2.                                                  *|
|*    2)  Enable the file system (Robot > Compile and Download ... > Optional File System)            *|
|*    3)  Set "Program Chooser.c" as the default, and all other programs (including this one)         *|
|*        should be compiled to the File System.                                                      *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    UART Port 2         none                VEX LCD Screen        Be sure to use both RX and TX.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//============================================| My Code |=============================================
task MyCode()
{
  while(true)
  {
    //-----------------------------------

      // Put your code here.

    //-----------------------------------

    wait10Msec(20); // Leave the wait statement at the end of this while loop to help the multitasking process.
  }
}
//====================================================================================================

















int nCurrentFileIndex;

//---------------------------------------| Select Next Program |--------------------------------------
bool bSelectNextProgram(int nDirection)
{
  //
  // Increment (or decrement) to the next valid file slot. Skip over empty file slots.
  //
  int nAttempts = 0;

  for (nAttempts = 0; nAttempts < kMaxNumbofFlashFiles; ++nAttempts)
  {
    nCurrentFileIndex += nDirection;
    if (nCurrentFileIndex < 1)
      nCurrentFileIndex = kNumbOfFiles - 1;
    if (nCurrentFileIndex >= kNumbOfFiles)
      nCurrentFileIndex = 1;
    if (bValidFile(nCurrentFileIndex))
      return true;
  }
  return false;
}
//----------------------------------------------------------------------------------------------------

//============================================| Chooser |=============================================
task Chooser()
{
  nCurrentFileIndex = 0;
  bLCDBacklight = true;
	PlaySound(soundFastUpwardTones);
  if (!bSelectNextProgram(+1))
	{
		// File system is empty

	  displayLCDCenteredString(1, "No programs");
		while (true)
		{
		  PlaySound(soundBlip);
		  wait1Msec(500);
	  }
	}
	displayLCDCenteredString(1, "Select A Pgm");
	wait1Msec(1000);

	while (true)
  {
    if (nLCDButtons & kButtonLeft)
    {
      bSelectNextProgram(-1);
      while (nLCDButtons != kNoButtons)
      {}
    }

    else if (nLCDButtons & kButtonRight)
    {
      bSelectNextProgram(+1);
      while (nLCDButtons != kNoButtons)
      {}
    }

    else if (nLCDButtons & kButtonRight)
    {
      bSelectNextProgram(+1);
    }


    else if (nLCDButtons & kButtonCenter)
    {
      // Start execution of current selection

      while (nLCDButtons != kNoButtons)
      {}
      setProgramNumber(nCurrentFileIndex);
    }

    // Display current selection on LCD

    displayFileName(0, nCurrentFileIndex);
    displayLCDPos(1, 0);
    displayNextLCDString("\F7     Run      \F6");// F6 and F7 are left, right arrows

    wait10Msec(20);
  }
  return;
}
//====================================================================================================


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  StartTask(Chooser);   // Start the 'Chooser' Task

  StartTask(MyCode);    // Start the 'MyCode' Task (user's code)

  while(true)           // Infinite loop to keep your program alive
  {
    wait1Msec(20);      // A short wait to help the multitasking process.
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
