#pragma config(Sensor, in1,    armLeft,        sensorPotentiometer)
#pragma config(Sensor, in2,    armRight,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  driveLeftSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  driveRightSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  mobileLeftSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  mobileRightSensor, sensorQuadEncoder)
#pragma config(Motor,  port1,           towerRightPrim, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           driveRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           coneLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           clawLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           towerLeftSecd, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           towerRightSecd, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           clawRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           coneRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           driveLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          towerLeftPrim, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Drive on power expander

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[driveLeftMotor] = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[driveRightMotor] = vexRT[Ch3];


    // Control speeds from variable to make changes easier
    int coneSpeed = 127;
    int towerSpeed = 127;
    int clawSpeed = 127;

	  //Tower Cone Control
    if(vexRT[Btn6U] == 1)
    {
      motor[towerRightPrim] = towerSpeed;
      motor[towerLeftPrim] = towerSpeed;
      motor[towerRightSecd] = towerSpeed;
      motor[towerLeftSecd] = towerSpeed;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[towerRightPrim] = (-1)*(towerSpeed);
      motor[towerLeftPrim] = (-1)*(towerSpeed);
      motor[towerRightSecd] = (-1)*(towerSpeed);
      motor[towerLeftSecd] = (-1)*(towerSpeed);
    }
    else
    {
      motor[towerRightPrim] = 0;
      motor[towerLeftPrim] = 0;
      motor[towerRightSecd] = 0;
      motor[towerLeftSecd] = 0;
    }

    //Mobile Goal Control
    if(vexRT[Btn5U] == 1)
    {
      motor[coneLeft] = coneSpeed;
      motor[coneRight] = coneSpeed;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[coneLeft] = (-1)*(coneSpeed);
      motor[coneRight] = (-1)*(coneSpeed);
    }
    else
    {
      motor[coneLeft] = 0;
      motor[coneLeft] = 0;
    }

    //Claw Motor Control
    if(vexRT[Btn8L] == 1)
    {
      motor[clawLeft] = clawSpeed;
      motor[clawRight] = clawSpeed;
    }
    else if(vexRT[Btn8R] == 1)
    {
      motor[clawLeft] = (-1)*(clawSpeed);
      motor[clawRight] = (-1)*(clawSpeed);
    }
    else
    {
      motor[clawLeft] = 0;
      motor[clawRight] = 0;
    }

	}
}
