#pragma config(Motor,  port1,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           backRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           armMotorRight, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           armMotorLeft,  tmotorVex393, openLoop)
#pragma config(Motor,  port6,           leftClaw,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightClaw,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          frontLeft,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

// Arthemus: Created by Ali Shariatmadari

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

// Sensitivity
float motorSensitivity = 2.0;
float armMotorSensitivity = 3.0;

void arcadeMove(float sensitivity){

    // Motor init
	  float RightY = vexRT[Ch2] / motorSensitivity;
		float RightX = vexRT[Ch1] / motorSensitivity;
		float LeftY = vexRT[Ch3] / motorSensitivity;
		float LeftX = vexRT[Ch4] / motorSensitivity;

		// Vector Addition and movement
		motor[frontLeft]  = (LeftY + LeftX) /2;
		motor[backLeft]  = (LeftY + LeftX) /2;
		motor[frontRight] = (LeftY - LeftX) /2;
		motor[backRight]  = (LeftY - LeftX) /2;
}

void armMovement(int speed, float sensitivity){
		motor[armMotorLeft] = speed / armMotorSensitivity;
		motor[armMotorRight] = speed / armMotorSensitivity;
}

void clawMovement(int speed, int close){
	if (close == 1){
		// Close Claw
		motor[rightClaw] = speed;
		motor[leftClaw] = speed;
	} else {
		//Open Claw
		motor[rightClaw] = -speed;
		motor[leftClaw] = -speed;
	}
}

void stopMovement(){
	  motor[frontLeft]  = 0;
		motor[backLeft]  = 0;
		motor[frontRight] = 0;
		motor[backRight]  = 0;
}


task usercontrol()
{

	while (true){

	  if (vexRT[Btn8D] == 1)
	  {
			// Movement
			arcadeMove(motorSensitivity);
	  }

		// ARM Movement
		if(vexRT[Btn5U] == 1)
    {
    	// Arm UP Movement
      armMovement(127, armMotorSensitivity);
    }
    else if(vexRT[Btn5D] == 1)
    {
    	// Arm Down Movement
      armMovement(-127, armMotorSensitivity);
    }
    else
    {
    	// Disengage Arm Motors
      motor[armMotorRight] = 0;
      motor[armMotorLeft] = 0;
    }

    // Close Claw
   	if (vexRT[Btn6U] == 1){
   			clawMovement(127, 1);
   	} else // Open Claw
   		if (vexRT[Btn6D] == 1){
   			clawMovement(127, 0);
  	}else
    {
    	// Disengage Claw Motors
      motor[leftClaw] = 0;
      motor[rightClaw] = 0;
    }

	}
}
