#pragma config(Sensor, dgtl1,  leftWheels,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightWheels,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftClaw,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armMotorRight1, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armMotorRight2, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armMotorLeft1, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armMotorLeft2, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           mobileGoal1,   tmotorVex393, openLoop)
#pragma config(Motor,  port9,           mobileGoal2,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightClaw,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
//Legit coding done by Erfan and Ali. Let's be real all the good stuff were made by Erfan
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

// Sensitivity
float motorSensitivity = 1.0;
float armMotorSensitivity = 1.0;
float clawMotorSensitivity = 3.0;
float mobileGoalLiftSense = 1.3;

void arcadeMove(float sensitivity){
		// Vector Addition and movement
		motor[leftDrive]  = (vexRT[Ch4] + vexRT[Ch3]) / motorSensitivity;
		motor[rightDrive] = (vexRT[Ch4] - vexRT[Ch3]) / motorSensitivity;
}

void tankDrive(float sensitivity){
	//Right side of the robot is controlled by the right joystick, Y-axis
  motor[leftDrive] = vexRT[Ch2];
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[rightDrive] = vexRT[Ch3];
}

void autoMovement(int speed){
	// Sync Wheels
		if(SensorValue[leftWheels] > SensorValue[rightWheels])
		{
			motor[leftDrive] = speed - (abs((SensorValue[leftWheels]) - (SensorValue[rightWheels])))/6;
			motor[rightDrive] = speed;
		}
		else if(SensorValue[leftWheels] < SensorValue[rightWheels])
		{
			motor[leftDrive] = speed;
			motor[rightDrive] = speed - (abs((SensorValue[leftWheels]) - (SensorValue[rightWheels]))/6);
		}
}

void armMovement(int speed, float sensitivity){
		motor[armMotorLeft1] = speed / armMotorSensitivity;
		motor[armMotorLeft2] = speed / armMotorSensitivity;
		motor[armMotorRight1] = speed / armMotorSensitivity;
		motor[armMotorRight2] = speed / armMotorSensitivity;
}

void mobileGoalLift(int speed, float sensitivity){
		motor[mobileGoal1] = speed / sensitivity;
		motor[mobileGoal2] = speed / sensitivity;
}

void clawMovement(int speed, int close){
	if (close == 1){
		// Close Claw
		motor[rightClaw] = speed;
		motor[leftClaw] = -speed;
	} else {
		//Open Claw
		motor[rightClaw] = -speed;
		motor[leftClaw] = speed;
	}
}

void stopMovement(){
	  motor[leftDrive]  = 0;
		motor[rightDrive]  = 0;
}

task usercontrol()
{

	while (true){

			// Movement
			arcadeMove(motorSensitivity);


		// ARM Movement
		if(vexRT[Btn5U] == 1)
    {
    	// Arm UP Movement
      armMovement(127, armMotorSensitivity);
    }
    else if(vexRT[Btn5D] == 1)
    {
    	// Arm Down Movement
      armMovement(-127, armMotorSensitivity);
    }

    else
    {
    	// Disengage Arm Motors
      motor[armMotorRight1] = 0;
      motor[armMotorRight2] = 0;
      motor[armMotorLeft1] = 0;
      motor[armMotorLeft2] = 0;
    }

    // Close Claw
   	if (vexRT[Btn6U] == 1){
   			clawMovement(127 / clawMotorSensitivity, 1);
   	} else // Open Claw
   		if (vexRT[Btn6D] == 1){
   			clawMovement(127 / clawMotorSensitivity, 0);
  	}else
    {
    	// Disengage Claw Motors
      motor[leftClaw] = 0;
      motor[rightClaw] = 0;
    }
		//Controller 2
 		//Mobile Goal control and TANK DRIVE

    /*
    //Tank Drive for Controller 2-full drive
			tankDrive(motorSensitivity);

		//Mobile Goal Control for Controller 2
			if (vexRT[Btn8D] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense);
    } else
    if (vexRT[Btn8U] == 1){
    	mobileGoalLift(-127, mobileGoalLiftSense);
    } else
    if (vexRT[Btn8DXmtr2] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense + 2.0);
    } else
    if (vexRT[Btn8UXmtr2] == 1){
    	mobileGoalLift(-127, mobileGoalLiftSense + 2.0);
    } else {
    	mobileGoalLift(0,0);
    }

    */

    if (vexRT[Btn8D] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense);
    } else
    if (vexRT[Btn8U] == 1){
    	mobileGoalLift(-127, mobileGoalLiftSense);
    } else
    if (vexRT[Btn8DXmtr2] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense + 2.0);
    } else
    if (vexRT[Btn8UXmtr2] == 1){
    	mobileGoalLift(-127, mobileGoalLiftSense + 2.0);
    } else {
    	mobileGoalLift(0,0);
    }
	}
}
