#pragma config(Sensor, dgtl1,  leftWheels,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightWheels,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftClaw,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           armMotorRight1, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armMotorRight2, tmotorVex393, openLoop)
#pragma config(Motor,  port6,           armMotorLeft1, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           armMotorLeft2, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           mobileGoal1,   tmotorVex393, openLoop)
#pragma config(Motor,  port9,           mobileGoal2,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightClaw,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
//Programmer: Erfan Ghafoori
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................
}

// Sensitivity
float motorSensitivity = 1.0;
float armMotorSensitivity = 2;
float clawMotorSensitivity = 2.1;
float mobileGoalLiftSense = 2;
int multi = 1;

void arcadeMove(float sensitivity){
		// Vector Addition and movement
		//Right side of the robot is controlled by the right joystick, Y-axis
  	if (multi == 1){
		motor[leftDrive] = -vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[rightDrive] = vexRT[Ch3];
  }

  else if (multi == -1){

  	motor[rightDrive] = -vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[leftDrive] = vexRT[Ch3];

	}


}

void tankDrive(float sensitivity){
	//Right side of the robot is controlled by the right joystick, Y-axis
  motor[rightDrive] = vexRT[Ch2Xmtr2] / sensitivity;
  //Left side of the robot is controlled by the left joystick, Y-axis
  motor[leftDrive] = -vexRT[Ch3Xmtr2] / sensitivity;
}

void autoMovement(int speed){
	// Sync Wheels
		if(SensorValue[leftWheels] > SensorValue[rightWheels])
		{
			motor[leftDrive] = speed - (abs((SensorValue[leftWheels]) - (SensorValue[rightWheels])))/6;
			motor[rightDrive] = speed;
		}
		else if(SensorValue[leftWheels] < SensorValue[rightWheels])
		{
			motor[leftDrive] = speed;
			motor[rightDrive] = speed - (abs((SensorValue[leftWheels]) - (SensorValue[rightWheels]))/6);
		}
}

void armMovement(int speed, float sensitivity){
		motor[armMotorLeft1] = speed / armMotorSensitivity;
		motor[armMotorLeft2] = speed / armMotorSensitivity;
		motor[armMotorRight1] = speed / armMotorSensitivity;
		motor[armMotorRight2] = speed / armMotorSensitivity;
}

void mobileGoalLift(int speed, float sensitivity){
		motor[mobileGoal1] = speed / sensitivity;
		motor[mobileGoal2] = speed / sensitivity;
}

void clawMovement(int speed, int close){
	if (close == 1){
		// Close Claw
		motor[rightClaw] = speed;
		motor[leftClaw] = -speed;
	} else {
		//Open Claw
		motor[rightClaw] = -speed;
		motor[leftClaw] = speed;
	}
}

void stopMovement(){
	  motor[leftDrive]  = 0;
		motor[rightDrive]  = 0;
}

task usercontrol()
{

	while (true){

		// Arcade Movement - Driver 1
		arcadeMove(motorSensitivity);

		// Arcade Movement - Driver 2
		//tankDrive(motorSensitivity);

		// ARM - Driver 1 EXCLUSIVE
		// ARM Movement
		if(vexRT[Btn6U] == 1)
    {
    	// Arm UP Movement
      armMovement(127, armMotorSensitivity);
    }
    else if(vexRT[Btn6D] == 1)
    {
    	// Arm Down Movement
      armMovement(-127, armMotorSensitivity);
    }
    else
    {
    	// Disengage Arm Motors
      motor[armMotorRight1] = 0;
      motor[armMotorRight2] = 0;
      motor[armMotorLeft1] = 0;
      motor[armMotorLeft2] = 0;
    }

    // Claw - Driver 1 EXCLUSIVE
    // Close Claw
   	if (vexRT[Btn5U] == 1){
   			clawMovement(127 / clawMotorSensitivity, 1);
   	}

   	else // Open Claw
   		if (vexRT[Btn5D] == 1){
   			clawMovement(127 / clawMotorSensitivity, 0);
  	}

  	else
    {
    	// Disengage Claw Motors
      motor[leftClaw] = 0;
      motor[rightClaw] = 0;
    }

    //Reverse
    if (vexRT[Btn7U] == 1){
    multi = 1;
    }

    //Reverse
    if (vexRT[Btn7D] == 1){
    multi = -1;
    }

		//Controller 2
    // Mobile Goal Lift - Driver 2 100%
    if (vexRT[Btn8U] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense);
    } else
    if (vexRT[Btn8D] == 1){
    	mobileGoalLift(-80, mobileGoalLiftSense);
    } else

    // Mobile Goal Lift - Driver 2 30%
    if (vexRT[Btn6UXmtr2] == 1){
    	mobileGoalLift(127, mobileGoalLiftSense + 2.0);
    } else
    if (vexRT[Btn5UXmtr2] == 1){
    	mobileGoalLift(-127, mobileGoalLiftSense + 2.0);
    } else {
    	mobileGoalLift(0,0);
    }
	}
}
