#pragma config(Sensor, dgtl1,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftMobile,     sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  rightMobile,    sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           backRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           coneClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           coneRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           mobileRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           mobileLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port7,           coneLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           mobileClawMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           backLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          frontLeftMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];


    // Control speeds from variable to make changes easier
    int mobileSpeed = 127;
    int towerSpeed = 127;
    int clawSpeed = 127;

	  //Tower Cone Control
    if(vexRT[Btn6U] == 1)
    {
      motor[coneRightMotor] = towerSpeed;
      motor[coneLeftMotor] = towerSpeed;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[coneRightMotor] = (-1)*(towerSpeed);
      motor[coneLeftMotor] = (-1)*(towerSpeed);
    }
    else
    {
      motor[coneRightMotor] = 0;
      motor[coneLeftMotor] = 0;
    }

    //Mobile Goal Control
    if(vexRT[Btn5U] == 1)
    {
      motor[mobileLeftMotor] = mobileSpeed;
      motor[mobileRightMotor] = mobileSpeed;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[mobileLeftMotor] = (-1)*(mobileSpeed);
      motor[mobileRightMotor] = (-1)*(mobileSpeed);
    }
    else
    {
      motor[mobileLeftMotor] = 0;
      motor[mobileRightMotor] = 0;
    }

    //Claw Motor Control
    if(vexRT[Btn7U] == 1)
    {
      motor[coneClawMotor] = clawSpeed;
    }
    else if(vexRT[Btn7D] == 1)
    {
      motor[coneClawMotor] = (-1)*(clawSpeed);
    }
    else
    {
      motor[coneClawMotor] = 0;
    }

    if(vexRT[Btn8R] == 1)
    {
      motor[mobileClawMotor] = clawSpeed;
    }
    else if(vexRT[Btn8L] == 1)
    {
      motor[mobileClawMotor] = (-1)*(clawSpeed);
    }
    else
    {
      motor[mobileClawMotor] = 0;
    }



	}
}
