#pragma config(Sensor, in1,    					rArmPotentiometer, 				sensorPotentiometer)
#pragma config(Sensor, in2,    					lArmPotentiometer, 				sensorPotentiometer)
#pragma config(Sensor, in3,    					lPivotPotentiometer, 			sensorPotentiometer)
#pragma config(Sensor, in4,   					rPivotPotentiometer, 			sensorPotentiometer)
#pragma config(Sensor, dgtl1,					  lArmSwitch,     					sensorTouch)
#pragma config(Sensor, dgtl2, 					rArmSwitch,     					sensorTouch)
#pragma config(Motor,  port2,           lArm1,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           lArm2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rArm1,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rArm2,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rPivot,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           lPivot,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 	Version 1.1

		Last Updated By
		Tony Tascioglu
		2016-11-01 11:10 AM
*/

task main()
{

int armSpeed = 0;
int lPotentiometer = 0;
int rPotentiometer = 0;
int pivotIdle = 0;

// Pivot




}

/* Changelogs
v1.0	2016-10-31		Created program
v1.1	2016-11-01		Added all potentiometers into pragma
*/
