#pragma config(Sensor, in1,    rPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    lPotentiometer, sensorPotentiometer)
#pragma config(Motor,  port2,           lArm1,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           lArm2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rArm1,         tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rArm2,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rPivot,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           lPivot,        tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int armSpeed = 0;
int lPotentiometer = 0;
int rPotentiometer = 0;
int idleRun = 0;

// Pivot




}
