#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftWheels,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightWheels,    sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor1,    tmotorVex393, openLoop)
#pragma config(Motor,  port2,           leftMotor3,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightMotor4,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           rightMotor5,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rightMotor6,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           leftTower,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           rightTower,    tmotorVex393, openLoop)
#pragma config(Motor,  port9,           lock,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port10,          leftMotor2,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
changelog: V1.5: improve holdClaw() function
*/
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

int hold = 0;

void forwardAuto(int distance, int speed)//distance in positive, remember to set sensor value to zero if needed; speed in positive
{
	while(SensorValue[leftWheels] < distance || SensorValue[rightWheels] < distance)
	{
		if(SensorValue[leftWheels] > SensorValue[rightWheels])
		{
			motor[leftMotor1] = speed;
			motor[leftMotor2] = speed;
			motor[leftMotor3] = speed;
			motor[rightMotor4] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor5] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor6] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
		}
		else if(SensorValue[leftWheels] < SensorValue[rightWheels])
		{
			motor[leftMotor1] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[leftMotor2] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[leftMotor3] = speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor4] = speed;
			motor[rightMotor5] = speed;
			motor[rightMotor6] = speed;
		}
		else if(SensorValue[leftWheels] == SensorValue[rightWheels])
		{
			motor[leftMotor1] = speed;
			motor[leftMotor2] = speed;
			motor[leftMotor3] = speed;
			motor[rightMotor4] = speed;
			motor[rightMotor5] = speed;
			motor[rightMotor6] = speed;
		}
	}
}

void backwardAuto(int distance, int speed)//distance in negative, remember to set sensor value to zero if needed; speed in positive
{
	while(SensorValue[leftWheels] > distance || SensorValue[rightWheels] > distance)
	{
		if(SensorValue[leftWheels] > SensorValue[rightWheels])
		{
			motor[leftMotor1] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[leftMotor2] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[leftMotor3] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor4] = -speed;
			motor[rightMotor5] = -speed;
			motor[rightMotor6] = -speed;
		}
		else if(SensorValue[leftWheels] < SensorValue[rightWheels])
		{
			motor[leftMotor1] = -speed;
			motor[leftMotor2] = -speed;
			motor[leftMotor3] = -speed;
			motor[rightMotor4] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor5] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
			motor[rightMotor6] = -speed + abs(SensorValue[leftWheels] - SensorValue[rightWheels]);
		}
		else if(SensorValue[leftWheels] == SensorValue[rightWheels])
		{
			motor[leftMotor1] = -speed;
			motor[leftMotor2] = -speed;
			motor[leftMotor3] = -speed;
			motor[rightMotor4] = -speed;
			motor[rightMotor5] = -speed;
			motor[rightMotor6] = -speed;
		}
	}
}

void stopMoving()
{
	motor[leftMotor1] = 0;
	motor[leftMotor2] = 0;
	motor[leftMotor3] = 0;
	motor[rightMotor4] = 0;
	motor[rightMotor5] = 0;
	motor[rightMotor6] = 0;
}

void armUp()
{
	motor[leftTower] = 127;
	motor[rightTower] = 127;
}

void armDown()
{
	motor[leftTower] = -63;
	motor[rightTower] = -63;
}

void armStop()
{
	motor[leftTower] = 0;
	motor[rightTower] =0 ;
}

void grab()
{
	motor[claw] = 127;
}

void holdClaw()
{
	while(true)
	{
		motor[claw] = 40;
		wait1Msec(1);
		motor[claw] = 0;
		wait1Msec(1);
	}
}

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
void pre_auton()
{
	motor[lock] = -60;
	SensorValue[leftWheels] = 0;
	SensorValue[rightWheels] = 0;
}
task autonomous()
{
	// remember to set sensor value (encoders) to zero if needed
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}
task usercontrol()
{

	while (true)
	{
		//driving system
			motor[leftMotor1] = vexRT[Ch3];
			motor[leftMotor2] = vexRT[Ch3];
			motor[leftMotor3] = vexRT[Ch3];
			motor[rightMotor4] = vexRT[Ch2];
			motor[rightMotor5] = vexRT[Ch2];
			motor[rightMotor6] = vexRT[Ch2];


		//six bar control.
		if(SensorValue[arm] > 289  && SensorValue[arm] < 2064 )
		{
			if(vexRT[Btn5U] == 1)
			{
				armUp();
			}
			else	if(vexRT[Btn5D] == 1)
			{
				armDown();
			}
			else
			{
				armStop();
			}
		}
		//goes up from the lowest position.
		else if(SensorValue[arm] > 2064)
   	{
   		if(vexRT[Btn5U] == 1)
   		{
   			armUp();
   		}
   		else
 			{
 				armStop();
   		}
   	}
    //goes down from the highest position
    else if(SensorValue[arm]< 289)
    {
 			if(vexRT[Btn5D] == 1)
 			{
 				motor[rightTower] = -127;
   			motor[leftTower] = -127;
   		}
   		else
   			{
   				armStop();
   			}
   		}
  	//lock

		//claw
   		while(vexRT[Btn6D] == 1)
   		{
   			motor[claw] = 40;
				wait1Msec(1);
				motor[claw] = 0;
				wait1Msec(1);
   		}
   		if(vexRT[Btn6U] == 1)
   		{
   			motor[claw] = 127;
   		}
   		else
   		{
   			motor[claw] = 0;
   		}

/*		//claw1
		if(vexRT[Btn8L] == 1)
		{
			motor[claw] = 30;
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[claw] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}

		//claw2
		if(vexRT[Btn8L] == 1)
		{
			holdClaw();
		}
		else if(vexRT[Btn6U] == 1)
		{
			motor[claw] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}

		//claw3
		if(vexRT[Btn6U] == 1)
		{
			motor[claw] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}

*/
	}
}
