#pragma config(Sensor, dgtl2,  ,               sensorVirtualCompass)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma noprolog

void testStringInialization();



task main()
{
  testStringInialization();
}
