#pragma config(Sensor, in1,    armSensor,      sensorPotentiometer)
#pragma config(Sensor, in2,    clawSensor,     sensorPotentiometer)
#pragma config(Sensor, in3,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  leftWheelsSensor, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightWheelsSensor, sensorQuadEncoder)
#pragma config(Motor,  port1,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port2,           backRight,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           claw1,         tmotorVex393, openLoop)
#pragma config(Motor,  port4,           towerAB,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           lock,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port7,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           towerCD,       tmotorVex393, openLoop)
#pragma config(Motor,  port9,           claw2,         tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          tower,         tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


/////////////////////////////////////////////////////////////////////
//
//
//
//
/////////////////////////////Robot Functions/////////////////////////
//
//
//
//
/////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////
//
/////////////////////////////Forward///////////////////////////////
//
///////////////////////////////////////////////////////////////////
void forwardAuto(int speed)//distance in positive, remember to set sensor value to zero if needed; speed in positive
{
		if(SensorValue[leftWheelsSensor] > SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = speed - (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[frontLeft] = speed - (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[backRight] = speed;
			motor[frontRight] = speed;
		}
		else if(SensorValue[leftWheelsSensor] < SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = speed;
			motor[frontLeft] = speed;
			motor[backRight] = speed - (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[frontRight] = speed - (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
		}
		else if(SensorValue[leftWheelsSensor] == SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = speed;
			motor[frontLeft] = speed;
			motor[backRight] = speed;
			motor[frontRight] = speed;
		}
}

///////////////////////////////////////////////////////////////////
//
/////////////////////////////Backward//////////////////////////////
//
///////////////////////////////////////////////////////////////////
void backwardAuto(int speed)//distance in negative, remember to set sensor value to zero if needed; speed in positive
{
		if(SensorValue[leftWheelsSensor] > SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = -speed;
			motor[frontLeft] = -speed;
			motor[backRight] = -speed + (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[frontRight] = -speed + (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
		}
		else if(SensorValue[leftWheelsSensor] < SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = -speed + (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[frontLeft] = -speed + (abs((SensorValue[leftWheelsSensor]) - (SensorValue[rightWheelsSensor])));
			motor[backRight] = -speed;
			motor[frontRight] = -speed;
		}
		else if(SensorValue[leftWheelsSensor] == SensorValue[rightWheelsSensor])
		{
			motor[backLeft] = -speed;
			motor[frontLeft] = -speed;
			motor[backRight] = -speed;
			motor[frontLeft] = -speed;
		}
}

void stopMoving()
{
	motor[frontLeft] = 0;
	motor[backLeft] = 0;
	motor[frontRight] = 0;
	motor[backRight] = 0;
}



void ccwRotationBothSide(int degree, int speed)//degree in positive, and speed in positive for both side, program will set them to negative
{
	int distance = 6*degree/2;
	while(SensorValue[leftWheelsSensor] > -distance && SensorValue[rightWheelsSensor] < distance)
	{
		motor[backLeft] = -speed;
		motor[frontLeft] = -speed;
		motor[backRight] = speed;
		motor[frontRight] = speed;
	}
}

void cwRotationBothSide(int degree,int speed)//degree in positive, and speed in positive for both side, program will set them to negative
{
	int distance = 6*degree/2;
	while(SensorValue[leftWheelsSensor] < distance && SensorValue[rightWheelsSensor] > -distance)
	{
		motor[backLeft] = speed;
		motor[frontLeft] = speed;
		motor[backRight] = -speed;
		motor[frontRight] = -speed;
	}
}






//pivot goes up
void up()
{
	motor[towerAB] = 127;
	motor[towerCD] = 127;
	motor[tower] = 127;
}

void upSlowly()
{
	motor[towerAB] = 25;
	motor[towerCD] = 25;
	motor[tower] = 25;
}

//pivot goes down
void down()
{
	motor[towerAB] = -127;
	motor[towerCD] = -127;
	motor[tower] = -127;
}

void downSlowly()
{
	motor[towerAB] = -10;
	motor[towerCD] = -10;
	motor[tower] = -10;
}

//pivot stays still
void holdArm()
{
	if (SensorValue[armSensor] > 600)
	{
		motor[towerAB] = 10;
		motor[towerCD] = 10;
		motor[tower] = 10;
	}
	else if(SensorValue[armSensor] < 600)
	{
		motor[towerAB] = 0;
		motor[towerCD] = 0;
		motor[tower] = 0;
	}
}

void clawClose(int clawSpeed)
{
	motor[claw1] = clawSpeed;
	motor[claw2] = clawSpeed;
}

void clawOpen(int clawSpeed)
{
	motor[claw1] = -clawSpeed;
	motor[claw2] = -clawSpeed;
}

void clawStop()
{
	motor[claw1] = 0;
	motor[claw2] = 0;
}





void defenseAuto()
{
	int clawAuto = 0;
	if(SensorValue[clawSensor] < 800)
		clawAuto = 1;
	else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
		clawAuto = 2;
	else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
		clawAuto = 0;
	else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
		clawAuto = 3;
	else if(SensorValue[clawSensor] >1700)
		clawAuto = 4;
	while(clawAuto == 1)
	{
		motor[claw1] = -40;
		motor[claw2] = -40;
		motor[backLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[frontLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[backRight] = 0 - SensorValue[rightWheelsSensor];
		motor[frontRight] = 0 - SensorValue[rightWheelsSensor];
		int clawAuto = 0;
		if(SensorValue[clawSensor] < 800)
			clawAuto = 1;
		else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
			clawAuto = 2;
		else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
			clawAuto = 0;
		else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
			clawAuto = 3;
		else if(SensorValue[clawSensor] >1700)
			clawAuto = 4;
	}
	while(clawAuto == 2)
	{
		motor[claw1] = -20;
		motor[claw2] = -20;
		motor[backLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[frontLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[backRight] = 0 - SensorValue[rightWheelsSensor];
		motor[frontRight] = 0 - SensorValue[rightWheelsSensor];
		if(SensorValue[clawSensor] < 800)
			clawAuto = 1;
		else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
			clawAuto = 2;
		else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
			clawAuto = 0;
		else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
			clawAuto = 3;
		else if(SensorValue[clawSensor] >1700)
			clawAuto = 4;
	}
	while(clawAuto == 3)
	{
		motor[claw1] = 40;
		motor[claw2] = 40;
		motor[backLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[frontLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[backRight] = 0 - SensorValue[rightWheelsSensor];
		motor[frontRight] = 0 - SensorValue[rightWheelsSensor];
		if(SensorValue[clawSensor] < 800)
			clawAuto = 1;
		else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
			clawAuto = 2;
		else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
			clawAuto = 0;
		else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
			clawAuto = 3;
		else if(SensorValue[clawSensor] >1700)
			clawAuto = 4;
	}
	while(clawAuto == 4)
	{
		motor[claw1] = 80;
		motor[claw2] = 80;
		motor[backLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[frontLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[backRight] = 0 - SensorValue[rightWheelsSensor];
		motor[frontRight] = 0 - SensorValue[rightWheelsSensor];
		if(SensorValue[clawSensor] < 800)
			clawAuto = 1;
		else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
			clawAuto = 2;
		else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
			clawAuto = 0;
		else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
			clawAuto = 3;
		else if(SensorValue[clawSensor] >1700)
			clawAuto = 4;
	}
	while(clawAuto == 0)
	{
		motor[claw1] = 0;
		motor[claw2] = 0;
		motor[backLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[frontLeft] = 0 - SensorValue[leftWheelsSensor];
		motor[backRight] = 0 - SensorValue[rightWheelsSensor];
		motor[frontRight] = 0 - SensorValue[rightWheelsSensor];
		if(SensorValue[clawSensor] < 800)
			clawAuto = 1;
		else if(SensorValue[clawSensor] >800 && SensorValue[clawSensor] < 1230)
			clawAuto = 2;
		else if(SensorValue[clawSensor] >1230 && SensorValue[clawSensor] < 1330)
			clawAuto = 0;
		else if(SensorValue[clawSensor] >1330 && SensorValue[clawSensor] < 1700)
			clawAuto = 3;
		else if(SensorValue[clawSensor] >1700)
			clawAuto = 4;
	}
}






/////////////////////////////////////////////////////////////////////
//
//
//
//
///////////////////////////LCD Display Program///////////////////////
//
//
//
//
/////////////////////////////////////////////////////////////////////
int autonomousMode = 0;
string autonomousChoice;
void autonomousSelection()
{
	bLCDBacklight = true;
	while(nLCDButtons != 2)
	{
		if(autonomousMode == 0)
			autonomousChoice = "No Autonomous";
		else if(autonomousMode == 1)
			autonomousChoice = "Autonomous 1L";
		else if(autonomousMode == 2)
			autonomousChoice = "Autonomous 1R";
		else if(autonomousMode == 3)
			autonomousChoice = "Autonomous 2L";
		else if(autonomousMode == 4)
			autonomousChoice = "Autonomous 2R";
		else if(autonomousMode == 5)
			autonomousChoice = "Autonomous 3";
		else if(autonomousMode == 6)
			autonomousChoice = "Autonomous 4L";
		else if(autonomousMode == 7)
			autonomousChoice = "Autonomous 4R";

		displayLCDCenteredString(0,autonomousChoice);
		displayLCDCenteredString(1,"<<   confirm  >>");
		if(nLCDButtons == 4)
		{
			autonomousMode++;
		}
		else if(nLCDButtons == 1)
		{
			autonomousMode--;
		}
		if(autonomousMode<0)
			autonomousMode = 7;
		else if(autonomousMode > 7)
			autonomousMode = 0;

			wait1Msec(200);
	}
	if(nLCDButtons == 2)
	{
		clearLCDLine(0);
		clearLCDLine(1);
			string mainBatteryVoltage, powerExpanderVoltage;
			displayLCDCenteredString(0,autonomousChoice);
			sprintf(mainBatteryVoltage, "%1.2f%c",nImmediateBatteryLevel/1000.0,'V');
			sprintf (powerExpanderVoltage, "%1.2f%c",SensorValue[powerExpander] /4/45.6, 'V');
			displayLCDString(1,0,"M:");
			displayLCDString(1,2,mainBatteryVoltage);
			displayLCDString(1,8,"PE:");
			displayLCDString(1,11,powerExpanderVoltage);
			wait1Msec(3000);
	}
}

task autonomousDisplayValue()
{
	clearLCDLine(0);
	clearLCDLine(1);
	while(true)
	{
		string mainBatteryVoltage, powerExpanderVoltage;
			displayLCDCenteredString(0,autonomousChoice);
			sprintf(mainBatteryVoltage, "%1.2f%c",nImmediateBatteryLevel/1000.0,'V');
			sprintf (powerExpanderVoltage, "%1.2f%c",SensorValue[powerExpander] /4/45.6, 'V');
			displayLCDString(1,0,"M:");
			displayLCDString(1,2,mainBatteryVoltage);
			displayLCDString(1,8,"PE:");
			displayLCDString(1,11,powerExpanderVoltage);
			wait1Msec(200);
	}
}

task driverControlDisplayValue()
{
	clearLCDLine(0);
	clearLCDLine(1);
	while(true)
	{
		string mainBatteryVoltage, powerExpanderVoltage;
		sprintf(mainBatteryVoltage, "%1.2f%c",nImmediateBatteryLevel/1000.0,'V');
		sprintf (powerExpanderVoltage, "%1.2f%c",SensorValue[powerExpander] /4/45.6, 'V');
		displayLCDString(0,3,"Main:");
		displayLCDString(0,8,mainBatteryVoltage);
		displayLCDString(1,2,"PowEx:");
		displayLCDString(1,8,powerExpanderVoltage);
		wait1Msec(200);
	}
}

///////////////////////////LCD Display Program Finish///////////////////////////////////






/////////////////////////////////////////////////////////////////////
//
//
//
//
///////////////////////////Autonomous Functions///////////////////////
//
//
//
//
/////////////////////////////////////////////////////////////////////

void autonomous1L()
{
	clearLCDLine(0);
	clearLCDLine(1);
	StartTask(autonomousDisplayValue);
	while(true)
	{
		defenseAuto();
	}
}
void autonomous1R()
{
	while(SensorValue[leftWheelsSensor] < 1000 || SensorValue[rightWheelsSensor] < 1000)
	{
		motor[backRight] = 127;
		motor[frontRight] = 127;
	}
	stopMoving();
}
void autonomous2L()
{
	while(SensorValue[leftWheelsSensor] > -1000 || SensorValue[rightWheelsSensor] > -1000)
	{
		motor[backLeft] = -127;
		motor[frontLeft] = -127;
	}
	stopMoving();
}
void autonomous2R()
{
	while(SensorValue[leftWheelsSensor] > -1000 || SensorValue[rightWheelsSensor] > -1000)
	{
		motor[backLeft] = -127;
		motor[frontLeft] = -127;
	}
	stopMoving();
}
void autonomous3()
{
	while(SensorValue[leftWheelsSensor] < 1000 || SensorValue[rightWheelsSensor] < 1000)
	{
		motor[backLeft] = 127;
		motor[backRight] = 127;
	}
	stopMoving();
}
void autonomous4L()
{
	while(SensorValue[leftWheelsSensor] < 1000 || SensorValue[rightWheelsSensor] < 1000)
	{
		motor[backLeft] = 127;
		motor[frontLeft] = 127;
		motor[backRight] = -127;
		motor[frontRight] = -127;
	}
	stopMoving();
}
void autonomous4R()
{
	while(SensorValue[leftWheelsSensor] < 1000 || SensorValue[rightWheelsSensor] < 1000)
	{
		motor[backLeft] = -127;
		motor[frontLeft] = -127;
		motor[backRight] = 127;
		motor[frontRight] = 127;
	}
	stopMoving();
}



/////////////////////////////////////////////////////////////////////////////////////////



void clearEncoders()
{
	SensorValue[leftWheelsSensor] = 0;
	SensorValue[rightWheelsSensor] = 0;
}

void pre_auton()
{
	//bLCDBacklight = true;
	//autonomousSelection();
	clearEncoders();
	motor[lock] = -30;
}
/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//prepare
	clearEncoders();
	while(SensorValue[armSensor] < 900)
	{
		up();
	}
	holdArm();
	while(SensorValue[clawSensor] > 1100)
	{
		clawClose(127);
	}
	clawStop();
	while(SensorValue[armSensor] > 480)
	{
		down();
	}
	holdArm();
	//forward for cube
	while(SensorValue[leftWheelsSensor] < 700 && SensorValue[rightWheelsSensor] < 700)
	{
		forwardAuto(80);
		clawOpen(14);
	}
	clawStop();
	stopMoving();
	wait1Msec(300);
	clawClose(90);
	wait1Msec(400);
	clawClose(30);
	while(SensorValue[armSensor] < 2200)
	{
		up();
	}
	holdArm();
	wait1Msec(300);
	clearEncoders();
	while(SensorValue[leftWheelsSensor] < 200 && SensorValue[rightWheelsSensor] < 200)
	{
		forwardAuto(30);
	}
	wait1Msec(300);
	clearEncoders();
	ccwRotationBothSide(45,70);//turn here, facing fence now
	stopMoving();
	wait1Msec(500);
	clearEncoders();
	while(SensorValue[leftWheelsSensor] < 450 && SensorValue[rightWheelsSensor] < 450)
	{
		forwardAuto(100);
	}
	while(SensorValue[leftWheelsSensor] < 600 && SensorValue[rightWheelsSensor] < 600)
	{
		forwardAuto(70);
		clawOpen(63);
	}
	stopMoving();
	while(SensorValue[clawSensor] < 1230)
	{
		clawOpen(63);//drop cube
	}
	clawStop();
	while(SensorValue[clawSensor] > 139)
	{
		clawClose(127);
	}
	clawStop();
	while(SensorValue[leftWheelsSensor] > 350 && SensorValue[rightWheelsSensor] > 350)
	{
		backwardAuto(50);
	}
	stopMoving();
	while(SensorValue[armSensor] > 1930)
	{
		down();
		clawOpen(90);
	}
	holdArm();
	while(SensorValue[clawSensor] < 930)
	{
		clawOpen(63);
	}
	clawStop();
	wait1Msec(100);
	while(SensorValue[leftWheelsSensor] < 630 && SensorValue[rightWheelsSensor] < 630)
	{
		forwardAuto(63);
	}
	stopMoving();
	while(SensorValue[armSensor] < 2050)
	{
		up();
	}
	holdArm();
	clearEncoders();
	while(true)
	{
		defenseAuto();
	}


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//
//                                 User Control Task
//
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	StartTask (driverControlDisplayValue);
	while (true)
	{

//////////////////////////////////////////////////////
//
//
//                     driving
//
//
//////////////////////////////////////////////////////



		int threshold = 15;
	 	if(abs(vexRT[Ch2]) > threshold)
			{
				motor[backRight] = vexRT[Ch2];
				motor[frontRight] = vexRT[Ch2];
			}
		else if(abs(vexRT[Ch2]) < threshold)
		{
			motor[backRight] = 0;
			motor[frontRight] = 0;
		}
		if(abs(vexRT[Ch3]) > threshold)
			{
				motor[backLeft] = vexRT[Ch3];
				motor[frontLeft] = vexRT[Ch3];
			}
		else if(abs(vexRT[Ch3]) < threshold)
		{
			motor[backLeft] = 0;
			motor[frontLeft] = 0;
		}


//////////////////////////////////////////////////////
//
//
//                     claw
//
//
//////////////////////////////////////////////////////





		if(vexRT[Btn6U] == 1)
		{
			clawClose(55);
		}
		else if(vexRT[Btn6D] == 1)
		{
			clawOpen(127);
		}
		else
		{
			clawStop();
		}


//////////////////////////////////////////////////////
//
//
//                six-bar / pivit
//
//
//////////////////////////////////////////////////////


			if(SensorValue[armSensor] < 2200 && SensorValue[armSensor] > 460)
		{
			if(vexRT[Btn5U] == 1)
				up();
			else if(vexRT[Btn5D] == 1)
				down();
			else
				holdArm();
		}
		else if(SensorValue[armSensor] > 2200)
		{
			if(vexRT[Btn5D] == 1)
				down();
			else
				holdArm();
		}
		else if(SensorValue[armSensor] < 460)
		{
			if(vexRT[Btn5U] == 1)
				up();
			else
				holdArm();
		}


		if(vexRT[Btn7U] == 1 || vexRT[Btn8U] == 1)
		{
			upSlowly();
		}
		else if(vexRT[Btn7D] == 1 || vexRT[Btn8D] == 1)
		{
			downSlowly();
		}
		else
		{
			holdArm();
		}


//////////////////////////////////////////////////////
//
//
//                     lock
//
//
//////////////////////////////////////////////////////



		if(vexRT[Btn7L] == 1 || vexRT[Btn8R] == 1)
		{
			motor[lock] = -111;
		}
		else if(vexRT[Btn7R] == 1 && vexRT[Btn8L] == 1)
		{
			motor[lock] = -30;
		}
	}
}
