#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           backLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port5,           backRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           sidewaysMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 2198X User Control Drive Program
// UPDATE: ADDED DEADZONE THRESHOLDS

task main()
{

int side = 0;
int forbackward = 0;
int threshold1 = 40;
int threshold2 = 30;

  while(1 == 1) // Loop following indefinetly
  {

  	if(abs(vexRT[Ch4]) > threshold1)
  	{
  		side = 127;
  	}
  	else
  	{
  		side = 0;
  	}
  	if (abs(vexRT[Ch3]) > threshold2)
  	{
  		forbackward = vexRT[Ch3];
  	}
  	else
  	{
  		forbackward = 0;
  	}

 		//Right side of the robot is controlled by the left joystick, Y-axis, minus the rotation from the x axis
    motor[frontRightMotor] = (forbackward - vexRT[Ch1]);
    motor[backRightMotor]  = (forbackward - vexRT[Ch1]);
    //Left side of the robot is controlled by the left joystick, Y-axis, plus the rotation from the x axis
    motor[frontLeftMotor] = (forbackward + vexRT[Ch1]);
    motor[backLeftMotor]  = (forbackward + vexRT[Ch1]);

    motor[sidewaysMotor] = side; // Allows the robot to move sideways, based on the

    //changelog set threshold for forward and backward movement.


	}

}
