#pragma config(Sensor, in1,    arm1,           sensorPotentiometer)
#pragma config(Sensor, in2,    arm2,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightMobile,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftMobile,     sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  leftDrive,      sensorQuadEncoder)
#pragma config(Motor,  port1,           mobileRightupMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           mobileRightdnMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           coneClawMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port4,           coneRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rightDriveMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           mobileLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port7,           coneLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port8,           mobileClawMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           backLeftMotor, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          frontLeftMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

//Right side of the robot is controlled by the right joystick, Y-axis
    motor[rightDriveMotor] = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[backLeftMotor] = vexRT[Ch3];
    motor[frontLeftMotor] = vexRT[Ch3];

        //motor[frontLeftMotor]  = (vexRT[Ch3] + vexRT[Ch4])/1;  // (y + x)/2
        //motor[backLeftMotor]  = (vexRT[Ch3] + vexRT[Ch4])/1; // (y + x)/2
        //motor[rightDriveMotor] = (vexRT[Ch3] - vexRT[Ch4])/1; // (y - x)/2

    // Control speeds from variable to make changes easier
    int mobileSpeed = 127;
    int towerSpeed = 127;
    int clawSpeed = 127;



      //Tower Cone Control
    // Slow dowm motors
    if(vexRT[Btn6D] == 1)
    {
      motor[coneRightMotor] = towerSpeed;
      motor[coneLeftMotor] = towerSpeed;
    }
    else if(vexRT[Btn6U] == 1)
    {
      motor[coneRightMotor] = (-1)*(towerSpeed);
      motor[coneLeftMotor] = (-1)*(towerSpeed);
    }
    else
    {
      motor[coneRightMotor] = 0;
      motor[coneLeftMotor] = 0;
    }

    //Mobile Goal Control

    // endcoder
    // + down
    // - up

    int rightInverse = (SensorValue[rightMobile])*-1;
    int leftInverse = (SensorValue[leftMobile])*-1;

   // int difference = ((SensorValue[rightMobile] - SensorValue[leftMobile])*(SensorValue[rightMobile] - SensorValue[leftMobile]))/3;
    int difference = 0;

    if(vexRT[Btn5D] == 1)
    {

   // if(SensorValue[rightMobile] < 200) {

    if(SensorValue[rightInverse] == SensorValue[leftInverse]) // If rightEncoder has counted the same amount as leftEncoder:
        {
            // Move Forward
        motor[mobileLeftMotor] = mobileSpeed;
        motor[mobileRightupMotor] = mobileSpeed;            // Left Motor is run at power level 80
        motor[mobileRightdnMotor] = mobileSpeed;
    }
        else if(SensorValue[rightInverse] > SensorValue[leftInverse])    // If rightEncoder has counted more encoder counts
        {
            // Turn slightly right
            motor[mobileLeftMotor] = mobileSpeed;
        motor[mobileRightupMotor] = mobileSpeed-difference;        // Left Motor is run at power level 80
         motor[mobileRightdnMotor] = mobileSpeed-difference;
        }
        else    // Only runs if leftEncoder has counted more encoder counts
        {
            // Turn slightly left
            motor[mobileLeftMotor] = mobileSpeed-difference;
            motor[mobileRightupMotor] = mobileSpeed;            // Left Motor is run at power level 60
            motor[mobileRightdnMotor] = mobileSpeed;
        }

    }

//    else {
 //       if(vexRT[Btn7D] == 1)
//    {
//        motor[mobileLeftMotor] = 127;
//      motor[mobileRightupMotor] = 127;
//      motor[mobileRightdnMotor] = 127;
 //     }
//  }
//  }

   else {
       if(vexRT[Btn5U] == 1)
   {
   //if(SensorValue[rightMobile] > -2200) {

   if(SensorValue[rightMobile] == SensorValue[leftMobile]) // If rightEncoder has counted the same amount as leftEncoder:
      {
            // Move Forward
        motor[mobileLeftMotor] = -1*mobileSpeed;
     motor[mobileRightupMotor] = -1*mobileSpeed;            // Left Motor is run at power level 80
     motor[mobileRightdnMotor] = -1*mobileSpeed;
      }
        else if(SensorValue[rightMobile] > SensorValue[leftMobile])    // If rightEncoder has counted more encoder counts
        {
            // Turn slightly right                           // Left Motor is run at power level 80
            motor[mobileLeftMotor] = -1*(mobileSpeed);
            motor[mobileRightupMotor] = -1*(mobileSpeed-difference);
            motor[mobileRightdnMotor] = -1*(mobileSpeed-difference);
        }
        else    // Only runs if leftEncoder has counted more encoder counts
        {
            // Turn slightly left
            motor[mobileLeftMotor] = -1*(mobileSpeed-difference);
        motor[mobileRightupMotor] = -1*(mobileSpeed);            // Left Motor is run at power level 60
        motor[mobileRightdnMotor] = -1*(mobileSpeed);
        }

    }

//    else {
//        if(vexRT[Btn7U] == 1)
 //   {
 //       motor[mobileLeftMotor] = -127;
 //     motor[mobileRightupMotor] = -127;
 //     motor[mobileRightdnMotor] = -127;
 //     }
 // }

 //   }
    else
    {
      motor[mobileLeftMotor] = 0;
      motor[mobileRightupMotor] = 0;
      motor[mobileRightdnMotor] = 0;
    }
   }

    if(vexRT[Btn7L] == 1)
    {
      motor[mobileLeftMotor] = clawSpeed;
    }
    if(vexRT[Btn7R] == 1)
    {
     motor[mobileRightupMotor] = clawSpeed;
     motor[mobileRightdnMotor] = clawSpeed;
    }

    //Claw Motor//


		 if(vexRT[Btn8L] == 1)
    {
      motor[coneClawMotor] = 30;
    }
    else if(vexRT[Btn8R] == 1)
    {
      motor[coneClawMotor] = (-1)*(30);
    }

    ///Mobile claw motor///
	 if(vexRT[Btn8D] == 1)
    {
      motor[mobileClawMotor] = 127;
    }
    else if(vexRT[Btn8U] == 1)
    {
      motor[mobileClawMotor] = (-1)*(127);
    }
    else
    {
      motor[mobileClawMotor] = -5;
      }
	}
}
