#pragma config(Motor,  port1,           frontLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          backRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	double motorSensitivity = 1.0;

	//R-SENSE OF 1.0 CAUSES STATIC ROTATION.
	double rotationSensitivity= 0.5;

	while (true){

		double LeftY = vexRT[Ch3] / motorSensitivity;
		double LeftX = vexRT[Ch4] / motorSensitivity;
		double RightY = vexRT[Ch2] / motorSensitivity;
		double RightX = vexRT[Ch1] / motorSensitivity;

		if (LeftY != 0){
			if (LeftX > 0){
				motor[frontRight] = LeftY;
				motor[backRight] = LeftY;
				motor[frontLeft] = LeftX / rotationSensitivity;
				motor[backLeft] = LeftX / rotationSensitivity;
			} else

			if (LeftX < 0){
				motor[frontRight] = LeftX / rotationSensitivity;
				motor[backRight] = LeftX / rotationSensitivity;
				motor[frontLeft] = LeftY;
				motor[backLeft] = LeftY;
			}
		} else

		if (LeftX > 0){
			motor[frontRight] = LeftX;
			motor[BackRight] = LeftX;
			motor[frontLeft] = -LeftX;
			motor[BackLeft] = -LeftX;
		}

	}


}
