#pragma config(Motor,  port1,           frontLeftMotor, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           towerLeft,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           mobileLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           mobile2Left,   tmotorVex393, openLoop)
#pragma config(Motor,  port6,           mobile2Right,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           mobileRight,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           towerRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          frontRightMotor, tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................


	// Drive system

	/*
	 * Sets the left motors to the value of
	 * channel 3 on the remote
	 */
	motor[backLeftMotor] = vexRT[Ch3];
	motor[frontLeftMotor] = vexRT[Ch3];

	// Right motors
	motor[backRightMotor] = vexRT[Ch2];
	motor[backRightMotor] = vexRT[Ch2];

	// Cone mechanism

	if (vexRT[Btn6U]) {

	motor[towerLeft] = 127;
	motor[towerRight] = 127;

	}
	else if (vexRT[Btn6D]) {

	motor[towerLeft] = -127;
	motor[towerRight] = -127;

	}

	else {

  motor[towerLeft] = 0;
	motor[towerRight] = 0;

}


// mobile goal

	if (vexRT[Btn5U]) {

	motor[mobileLeft] = 127;
	motor[mobileRight] = 127;
	motor[mobile2Left] = 127;
	motor[mobile2Right] = 127;

	}
	else if (vexRT[Btn5D]) {

	motor[mobileLeft] = -127;
	motor[mobileRight] = -127;
	motor[mobile2Left] = -127;
	motor[mobile2Right] = -127;

	}

	else {

  motor[mobileLeft] = 0;
	motor[mobileRight] = 0;
	motor[mobile2Left] = 0;
	motor[mobile2Right] = 0;

}

	}
}
